language: ruby
rvm:
- 2.2.4
env:
  - DB=mysql
script:
  - RAILS_ENV=test bundle exec rake db:setup --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database currency_ping_test'
# caches bundler dependencies for speedy builds
cache: bundler
bundler_args: --without production
sudo: false